acid-splash.dnd
dancing-lights.dnd
daze.dnd
detect-magic.dnd
disrupt-undead.dnd
electroic-jolt.dnd
flare.dnd
ghost-sound.dnd
light.dnd
mage-hand.dnd
open-close.dnd
prestidigitation.dnd
ray-of-frost.dnd
reload.dnd
sonic-snap.dnd
stick.dnd
animate-rope.dnd
animate-skeletons.dnd
benign-transposition.dnd
burning-hands.dnd
cause-fear.dnd
charm-person.dnd
color-spray.dnd
corrosive-graspe.dnd
detect-secret-doors.dnd
disguise-self.dnd
expeditious-retreat.dnd
feather-fall.dnd
floating-disk.dnd
grease.dnd
hypnotism.dnd
identify.dnd
jump.dnd
lesser-elemental-orb.dnd
mage-armor.dnd
magic-missile.dnd
magic-weapon.dnd
obscuring-mist.dnd
protection-from-chaos-evil-good-law.dnd
shield.dnd
shocking-grasp.dnd
silent-image.dnd
sleep.dnd
unseen-servant.dnd
acid-arrow.dnd
animate-zombies.dnd
baleful-transposition.dnd
blindness-deafness.dnd
blur.dnd
combust.dnd
darkness.dnd
daze-monster.dnd
electric-loop.dnd
enhance-ability.dnd
false-life.dnd
flaming-sphere.dnd
fog-cloud.dnd
ghoul-touch.dnd
gust-of-wind.dnd
hideous-laughter.dnd
hypnotic-pattern.dnd
invisibility.dnd
knock.dnd
minor-image.dnd
mirror-image.dnd
protection-from-arrows.dnd
pyrotechnics.dnd
scare.dnd
scorching-ray.dnd
see-invisibility.dnd
shatter.dnd
snowball-swarm.dnd
animate-ghouls.dnd
blink.dnd
chain-missiles.dnd
daylight.dnd
deep-slumber.dnd
dispel-magic.dnd
displacement.dnd
fireball.dnd
flame-arrow.dnd
fly.dnd
haste.dnd
heroism.dnd
hold-person.dnd
invisibility,-10-radius.dnd
lightning-bolt.dnd
mass-mage-armor.dnd
mass-shield.dnd
magic-circle-against-chaos-evil-good-law.dnd
major-image.dnd
reverse-arrows.dnd
shrink-item.dnd
sleet-storm.dnd
slow.dnd
suggestion.dnd
vampiric-touch.dnd
web.dnd
wind-gale.dnd
charm-monster.dnd
cone-of-fire.dnd
confusion.dnd
crushing-despair.dnd
dimension-door.dnd
earthbind.dnd
elemental-orb.dnd
fear.dnd
fire-shield.dnd
lesser-globe-of-invulnerability.dnd
ice-storm.dnd
illusory-wall.dnd
greater-invisibility.dnd
greater-flaming-sphere.dnd
phantasmal-killer.dnd
remove-curse.dnd
resilient-sphere.dnd
shout.dnd
stinking-cloud.dnd
stoneskin.dnd
wall-of-fire.dnd
wall-of-ice.dnd
